name: Michael Sippey
description: Michael Sippey's blog, published semi-regularly since 1995.
url: https://sippey.com
markdown: kramdown
highlighter: rouge
plugins: 
  - jekyll-archives
  - jekyll-paginate-v2
  - jekyll-feed
pagination: 
  enabled: true
  per_page: 20
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: 'true'
autopages:
  enabled: false
jekyll-archives:
  enabled: 
    - month
  permalinks: 
    month: '/:year/:month/'
  layout: archives

timezone: America/Los_Angeles
algolia:
  application_id: ALIH66MWZH
  index_name: sippeydotcom
  search_only_api_key: c2853a177366a5d9612dbd0445d9e79b

feed:
  path: rss.xml