name: Michael Sippey
description: this is @sippey's blog
url: https://sippey.com
markdown: kramdown
highlighter: rouge
paginate : 20
paginate_path: "page/:num"
plugins: [jekyll-paginate]
timezone: America/Los_Angeles
algolia:
  application_id: ALIH66MWZH
  index_name: sippeydotcom
  search_only_api_key: c2853a177366a5d9612dbd0445d9e79b